name: Compile Chess Engine
permissions:
  contents: write

on:
  - workflow_dispatch

jobs:
  build:
    name: Convert Rust Chess to Luau
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone Rust Chess Repository
        run: |
          git clone https://github.com/Someon1e/encrustant.git

      - name: Install Rust and Binaryen (wasm-opt)
        run: |
          rustup update stable
          rustup target add wasm32-unknown-unknown
          sudo apt update && sudo apt install -y binaryen

      - name: Build Rust Chess to WASM
        run: |
          cd encrustant/encrustant
          cargo build --release --target wasm32-unknown-unknown

      - name: Run wasm-opt
        run: |
          cd encrustant/encrustant/target/wasm32-unknown-unknown/release/
          wasm-opt -O4 encrustant.wasm -o encrustant-opt.wasm

      - name: Install Wasynth (wasm2luau)
        run: |
          cargo install --git https://github.com/Rerumu/Wasynth codegen-luau

      - name: Convert WASM to Luau
        run: |
          wasm2luau encrustant/encrustant/target/wasm32-unknown-unknown/release/encrustant-opt.wasm > src/shared/chess/engine/wasm/compiled.luau

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/shared/chess/engine/wasm/compiled.luau
          git commit -m "feat: Update chess engine"
          git push
